<h1 class="mb-4 text-center"><?= $this->escapeHtml($this->pageTitle ?? 'Fallback 2') ?></h1>

<a href="<?= $this->url('product', ['action' => 'add']) ?>" class="btn btn-primary mb-3">Ajouter un produit</a>
<?php if (empty($this->products)): ?>
    <p>Aucun produit disponible pour le moment.</p>
    <?php else: ?>
       <!-- TODO : Hauteur fixe a determiner pour aligner les cartes -->
    <div class="row row-cols-1 row-cols-md-4 g-4"> <?php foreach ($this->products as $product): ?>
            <div class="col">
                <div class="card">
                    <img src="<?= $this->escapeHtmlAttr($product->getImg() ?? 'https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg') ?>"
                        class="card-img-top object-fit-cover" alt="<?= $this->escapeHtml($product->getName()) ?>">
                    <div class="card-body">
                        <div class="card-body">
                            <h5 class="card-title text-center text-primary fw-bold"><?= $this->escapeHtml($product->getName()) ?></h5>
                            <p class="card-text"><?= $this->escapeHtml($product->getDescription() ?? '') ?></p>
                            <p class="card-text"><small
                                    class="text-body-secondary"><?= number_format($product->getPrice(), 2, ',', ' ') ?>
                                    €</small></p>
                        </div>


                        <a href="<?= $this->url('product', ['action' => 'view', 'id' => $product->getId()]) ?>"
                            class="btn btn-primary btn-sm">
                            Voir
                        </a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

